env:
  es6: true
  node: true
  jest: true
plugins:
  - flowtype
  - jest
extends:
  - "eslint:recommended"
  - "plugin:flowtype/recommended"
  - "plugin:jest/recommended"
parser: babel-eslint
parserOptions:
  sourceType: module
  ecmaVersion: 6
  ecmaFeatures:
    impliedStrict: true
    jsx: true
rules:
  no-useless-escape: 2
  handle-callback-err: 2
  no-fallthrough: 2
  no-new-require: 2
  max-len:
    - 2
    - 160
  camelcase: 0
  require-jsdoc: 0
  valid-jsdoc: 0
  prefer-spread: 1
  prefer-rest-params: 1
  linebreak-style: 0
  quote-props:
    - error
    - as-needed
